server:
  port: 801

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://chunyupingtai.mysql.rds.aliyuncs.com/chunyu?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Admin!123
      #type: com.alibaba.druid.pool.DruidDataSource
     #driverClassName: oracle.jdbc.OracleDriver
     #url: jdbc:oracle:thin:@139.196.93.105:1521/orcl
     #username: vms
     #password: vms123456
    #oracle配置
    #    driverClassName: oracle.jdbc.OracleDriver
    #    url: jdbc:oracle:thin:@47.100.206.162:1521:xe
    #    username: renren
    #    password: 123456
    #SQLServer配置
    #    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=renren_fast
    #    username: sa
    #    password: 123456
    ##PostgreSQL配置
    #driverClassName: org.postgresql.Driver
    #url: jdbc:postgresql://47.102.131.171:5432/temptest
    #username: temptest
    #password: temptest
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/


mybatis:
  mapperLocations: classpath:mapper/**/*.xml


pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql】
renren:
  database: mysql

